name: Continuous Integration

on:
  push:
    paths-ignore:
      - "**/README.md"
    branches:
      - master
  pull_request:
    branches: ["**"]
  workflow_dispatch:
  workflow_call:

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  rust_toolchain: stable

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.rust_toolchain }}
        components: rustfmt, clippy, rust-src
        
    - name: Setup | Checkout
      uses: actions/checkout@v4

    - name: Build | Compile
      run: cargo build

  
  check-format:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.rust_toolchain }}

    - name: Setup | Checkout
      uses: actions/checkout@v4

    - name: Check | Fmt Check
      run: cargo fmt -- --check

  
  check-clippy:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.rust_toolchain }}

    - name: Setup | Checkout
      uses: actions/checkout@v4

    - name: Check | Clippy
      run: cargo clippy --no-deps -- -Dwarnings


  test:
    runs-on: ubuntu-latest
    steps:
    - name: Setup | Rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env.rust_toolchain }}

    - name: Setup | Checkout
      uses: actions/checkout@v4

    - name: Test | Run
      run: cargo test
